### ISSUE TITLE
How to compute the self.means and self.stds in dpp_loss_layer.py file?

### ISSUE THREAD

**Issue by yaokeepmoving** [azadis/LDDP#1]
I am confused about how to compute the self.means and self.stds in the  dpp_loss_layer.py file. I would be very grateful if someone give me some details.

```python
        self.sim_classes = pickle.load(open(cfg.TRAIN.similarity_path,"r"))
        K = bottom[1].data.shape[1] # number of categories
        self.means = np.reshape(bottom[7].data,(K,4))
        self.stds = np.reshape(bottom[8].data,(K,4))
        self.stds[0,:] = np.ones(((self.stds).shape[1],))

**Comment by azadis** [comment]
means and stds are the outputs of the first input-data layer (top[3] and top[4]) which are passed into the dpploss layer as bottom[7] and bottom[8]  ( e.g. in this [train_dpp.prototxt](https://github.com/azadis/py-faster-rcnn/blob/35548aec0ab123147a098483af2c1a6dcc8ebffc/models/pascal_voc/VGG_CNN_M_1024/LDDP_end2end/train_dpp.prototxt) ).
Computation of means and stds are done in the [roi_data_layer](https://github.com/azadis/py-faster-rcnn/blob/35548aec0ab123147a098483af2c1a6dcc8ebffc/lib/roi_data_layer/roidb.py#L47).

**Comment by yaokeepmoving** [comment]
@azadis I sincerely appreciate your precise reply and it helps me a lot!
