### ISSUE TITLE
How to train own data with LDDP?

### ISSUE THREAD

**Issue by RichardMrLu** [azadis/LDDP#4]
I changed their class_num,but it crashed down:

sim_class_0[1:K,1:K] = self.sim_classed #include sims for class 0
ValueError: could not broadcast input array from shape(20,20) into shape (3,3)

I find it read by Semantic_Similarity.ipynb ,I changed info.json but till crashed by this problem.
My data are 4 classes, how to change files to made it trained well? 
Thanks for your answer.

**Comment by azadis** [comment]
Have you updated your pickle file too?  You should make yours through the Semantic_Similarity.ipynb (uncomment the one line commented out!)
Then update your config file:
https://github.com/azadis/py-faster-rcnn/blob/35548aec0ab123147a098483af2c1a6dcc8ebffc/experiments/cfgs/pascal_voc/LDDP_end2end.yml#L11

or directly point to your updated similarity_path in your bash script. https://github.com/azadis/py-faster-rcnn/blob/35548aec0ab123147a098483af2c1a6dcc8ebffc/experiments/scripts/LDDP_end2end.sh

**Comment by azadis** [comment]
Have you updated your pickle file too? You should make yours through the Semantic_Similarity.ipynb (uncomment the one line commented out with other necessary changes you have in your data set!)
Then update your config file:
https://github.com/azadis/py-faster-rcnn/blob/35548aec0ab123147a098483af2c1a6dcc8ebffc/experiments/cfgs/pascal_voc/LDDP_end2end.yml#L11

or directly point to your updated similarity_path in your bash script. https://github.com/azadis/py-faster-rcnn/blob/35548aec0ab123147a098483af2c1a6dcc8ebffc/experiments/scripts/LDDP_end2end.sh

**Comment by RichardMrLu** [comment]
Thanks! I read Semantic_Similarity.ipynb ,it opened 3 files: imagenet_count.txt、imagenet_tree.txt、imagenet_words.txt，how to create own dataset version?

**Comment by azadis** [comment]
Which categories do you have in your dataset? Are they a subset of Pascal or COCO categories? or even included in the 1000 classes of Imagenet?

**Comment by RichardMrLu** [comment]
Chinese traffic signs,include 3 classes: warning.prohibitory,mandatory. They are not a subset.

**Comment by azadis** [comment]
no need to change those text files. These files contain information regarding Imagenet tree and its hierarchy. You should look for the most similar category in

**Comment by azadis** [comment]
so in that case, you should consider your own new heuristic to measure similarities between these three categories (instead of Imagenet hierarchies)! or just for simplicity, assume there is no semantic similarity between them and save an identity matrix as your similarity pickle file.

**Comment by RichardMrLu** [comment]
Thanks for your answer.Is there any else paper explain Semantic_Similarity_Matrix? I didn't read any articles about Semantic_Similarity_Matrix..

**Comment by azadis** [comment]
https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/37065.pdf
and
https://arxiv.org/pdf/1510.02949.pdf
are two examples, but these are both for large-scale data sets. Anyways, since the number of categories for your case is very small, you can just define a similarity matrix between different categories based on your own estimation of similarities between your three labels.

**Comment by RichardMrLu** [comment]
I’m truly grateful for your help，I will try to do it.

**Comment by zqdeepbluesky** [comment]
@RichardMrLu Hey, have you solved the problem of training your own dataset by setting your own Semantic_Similarity_Matrix?
